# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

GIT_TOKEN: Vi2HmVz66srX5iUT7quU6FvhaRvsZw4FyQvLC2AagWw=
corsAllowOrigin: https://gitapi.capagcuan.org
tag: latest

node:
  repository: travissouth/gitapi
  pullPolicy: Always
  replicaCount: 1
  maxReplicas: 20
  targetAverageUtilization: 50
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
